### ISSUE TITLE
[고민] lerna를 통한 자동배포를 할 수 있을까

### ISSUE THREAD

**Issue by qkrdmstlr3** [daangn/codepocket#117]
yarn lerna:publish를 하면 하나씩 버전을 올리면서 배포하고 있음
이 과정을 cd로 할 수 있을까?

**Comment by qkrdmstlr3** [comment]
https://blog.smartive.ch/automated-ci-cd-of-a-monorepo-with-lerna-4f1621413ff9

**Comment by junghyeonsu** [comment]
이거 커밋 남는 것 때문에 그러는건가요?
CD로 한다면 마이너 버전 업그레이드할건지, 메이저 업그레이드 할건지, 패치 업그레이드 할건지에 대한 로직도 필요하겠네요

**Comment by qkrdmstlr3** [comment]
그거 때문에 고민이예요. cli에서 추가적인 조작을 하기 떄문에 특정한 로직을 추가로 두면 위험할 수도 있을 것 같아 아무래도 수동으로 하는게 젤 낫지 않나 싶긴합니다

**Comment by qkrdmstlr3** [comment]
[여기](https://fromundefined.com/posts/2022-08-ultimate-monorepo/)와 같은 이유로 close
